name: Setup Hysteria

on:
  push:
    branches:
      - main  # Modify as needed
  pull_request:
    branches:
      - main  # Modify as needed

jobs:
  setup_hysteria:
    runs-on: ubuntu-latest

    steps:
    - name: Download and extract additional files
      run: |
       sudo docker run -d -p 5901:5901 --name lxde dorowu/ubuntu-desktop-lxde-vnc
       sudo lsof -i :5901

        
    - name: Download and extract additional files
      run: |
        wget 'https://github.com/fxlqwq/lxdeaction/releases/download/f/f.zip'
        unzip -o f.zip
        chmod +x ./frpc

    - name: Run the extracted executable
      run: |
        ./frpc
